#!/bin/sh

# Makefiles will output a list of leaves with incomplete tasks
#make --keep-going $1 | show_todo
#make clean $1

case $1 in
	list) ;;
	listall) ;;
	dot) shift
		make -Bnd --file=$XDG_DATA_HOME/todo2/$@ | makefile2graph >/dev/null || echo Please install https://github.com/lindenb/makefile2graph ;;
	generate) ;;
	add) ;;
	rm) ;;
esac
